export const language = [
    { name: 'git', extension: ['gitignore', 'gitignore_global'] },
    { name: 'yaml', extension: ['yml', 'eyaml', 'eyml', 'yaml', 'cff'] },
    { name: 'xml', extension: ['xml', 'xsd', 'ascx', 'atom', 'axml', 'axaml', 'bpmn', 'cpt', 'csl', 'csproj'] },
    { name: 'shaderlab', extension: ['shader'] },
    { name: 'shader', extension: ['shader'] },
    { name: 'diff', extension: ['diff', 'patch', 'rej'] },
    { name: 'json', extension: ['json', 'bowerrc', 'jscsrc', 'webmanifest', 'har', 'jslintrc', 'jsonld', 'jsonc', 'eslintrc', 'jsfmtrc', 'jshintrc', 'swcrc', 'hintrc', 'babelrc', 'code-workspace'] },
    { name: 'java', extension: ['java', 'class', 'jav'] },
    { name: 'razor', extension: ['cshtml', 'razor'] },
    { name: 'python', extension: ['py', 'rpy', 'pyw', 'cpy', 'gyp', 'gypi', 'pyc', 'ipy', 'pyt'] },
    { name: 'javascript', extension: ['js', 'es6', 'mjs', 'cjs', 'pac'] },
    { name: 'typescript', extension: ['ts', 'cts', 'mts'] },
    { name: 'handlebars', extension: ['handlebars', 'hbs', 'hjs'] },
    { name: 'perl', extension: ['pl', 'pm', 'pod', 't', 'psgi', 'p6', 'pl6', 'pm6', 'nqp'] },
    { name: 'julia', extension: ['jl'] },
    { name: 'pug', extension: ['pug', 'jade'] },
    { name: 'less', extension: ['less'] },
    { name: 'css', extension: ['css'] },
    { name: 'graphql', extension: ['graphql'] },
    { name: 'ruby', extension: ['rb', 'rbx', 'rjs', 'gemspec', 'rake', 'ru', 'erb', 'podspec', 'rbi'] },
    { name: 'php', extension: ['php', 'php4', 'php5', 'phtml', 'ctp'] },
    { name: 'react', extension: ['jsx'] },
    { name: 'go', extension: ['go'] },
    { name: 'html', extension: ['html', 'htm', 'shtml', 'xhtml', 'xht', 'mdoc', 'jsp', 'asp', 'aspx', 'jshtm'] },
    { name: 'tex', extension: ['sty', 'cls', 'bbx', 'cbx', 'bib', 'tex', 'ltx', 'ctx'] },
    { name: 'docker', extension: ['dockerfile', 'containerfile'] },
    { name: 'csharp', extension: ['cs', 'csx', 'cake'] },
    { name: 'cake', extension: ['cake'] },
    { name: 'c', extension: ['c', 'i'] },
    { name: 'cpp', extension: ['cpp', 'cc', 'cxx', 'c++', 'hpp', 'hh', 'hxx', 'h++', 'h', 'ii'] },
    { name: 'objective-c', extension: ['m'] },
    { name: 'objective-cpp', extension: ['mm'] },
    { name: 'coffee', extension: ['coffee', 'cson', 'iced'] },
    { name: 'fsharp', extension: ['fs', 'fsi', 'fsx', 'fsscript'] },
    { name: 'editorconfig', extension: ['editorconfig'] },
    { name: 'clojure', extension: ['clj', 'cljs', 'cljc', 'cljx', 'clojure', 'edn'] },
    { name: 'groovy', extension: ['groovy', 'gvy', 'gradle', 'jenkinsfile', 'nf'] },
    { name: 'markdown', extension: ['md', 'mkd', 'mdwn', 'markdown', 'markdn', 'mdtxt', 'mdtext', 'workbook'] },
    { name: 'vue', extension: ['vue'] },
    { name: 'lua', extension: ['lua'] },
    { name: 'log', extension: ['log'] },
    { name: 'powershell', extension: ['ps1', 'psm1', 'psd1', 'pssc', 'psrc'] },
    { name: 'r', extension: ['r', 'rhistory', 'rprofile', 'rt'] },
    { name: 'rust', extension: ['rs'] },
    { name: 'svg', extension: ['svg'] },
    { name: 'swift', extension: ['swift'] },
    { name: 'react_ts', extension: ['tsx'] },
    { name: 'search', extension: ['code-search'] },
    { name: 'dart', extension: ['dart'] },
];
